const violations = [
  {
    article: "Άρθρο 7 παρ.11β | Ρ-2 STOP",
    desc: "Παραβίαση πινακίδας STOP (υποχρεωτική διακοπή πορείας)",
    category: "Ε4",
    seso_points: 19,
    license_removal: 60,
    plates_removal: 0,
    payment_deadline_days: 60,
    payment_authority: "DOU",
    payment_required_for_return: true,
    fines: { car: 700, truck_low: 700, truck_high: 1200, bus: 1200, moto: 350 },
    exceptions: "Αν προκληθεί ατύχημα: αφαίρεση 60 ημέρες + ποινικές κυρώσεις",
    keywords: ["stop", "διακοπή", "προτεραιότητα"]
  },
  {
    article: "Άρθρο 9 παρ.1β | Ερυθρός σηματοδότης",
    desc: "Διέλευση με ερυθρό φωτεινό σηματοδότη",
    category: "Ε4",
    seso_points: 20,
    license_removal: 60,
    plates_removal: 0,
    payment_deadline_days: 60,
    payment_authority: "DOU",
    payment_required_for_return: true,
    fines: { car: 700, truck_low: 700, truck_high: 1200, bus: 1200, moto: 350 },
    exceptions: "",
    keywords: ["κόκκινο", "φανάρι", "σηματοδότηση", "ερυθρό"]
  },
  {
    article: "Άρθρο 24 παρ.9γ | Υπέρβαση ταχύτητας >50 km/h",
    desc: "Υπέρβαση ορίου ταχύτητας άνω των 50 km/h από το ανώτατο όριο",
    category: "Ε4",
    seso_points: 20,
    license_removal: 60,
    plates_removal: 0,
    payment_deadline_days: 60,
    payment_authority: "DOU",
    payment_required_for_return: true,
    fines: { car: 700, truck_low: 700, truck_high: 1200, bus: 1200, moto: 350 },
    exceptions: "Για ταχύτητα >200 km/h: πρόστιμο 2.000€, αφαίρεση άδειας 1 έτος",
    keywords: ["ταχύτητα", "υπέρβαση", "km/h", "όριο"]
  },
  {
    article: "Άρθρο 24 παρ.9α | Υπέρβαση ταχύτητας έως 20 km/h",
    desc: "Υπέρβαση ορίου ταχύτητας έως 20 km/h",
    category: "Ε2-Α",
    seso_points: 4,
    license_removal: 0,
    plates_removal: 0,
    payment_deadline_days: 60,
    payment_authority: "DOU",
    payment_required_for_return: false,
    fines: { car: 150, truck_low: 150, truck_high: 150, bus: 150, moto: 75 },
    exceptions: "",
    keywords: ["ταχύτητα", "υπέρβαση", "ελαφρά"]
  },
  {
    article: "Άρθρο 46 παρ.7α | Αλκοόλ 0,50-0,80 g/l",
    desc: "Οδήγηση υπό επήρεια αλκοόλ (0,50-0,80 g/l αίματος ή 0,25-0,40 mg/l εκπνεόμενου)",
    category: "Ε3-Β",
    seso_points: 7,
    license_removal: 30,
    plates_removal: 0,
    payment_deadline_days: 60,
    payment_authority: "DOU",
    payment_required_for_return: true,
    fines: { car: 350, truck_low: 350, truck_high: 700, bus: 700, moto: 175 },
    exceptions: "Επαγγελματίες οδηγοί: όριο 0,20 g/l. Ακινητοποίηση οχήματος.",
    keywords: ["αλκοόλ", "μέθη", "ποτό", "οινοπνεύματος"]
  },
  {
    article: "Άρθρο 38 παρ.2ιστ | Στάθμευση σε ράμπα ΑμεΑ",
    desc: "Στάθμευση σε θέση όπου βρίσκεται ράμπα διάβασης ΑμεΑ",
    category: "Ε2-Β",
    seso_points: 0,
    license_removal: 0,
    plates_removal: 70,
    payment_deadline_days: 15,
    payment_authority: "OTA",
    payment_required_for_return: true,
    fines: { car: 150, truck_low: 150, truck_high: 150, bus: 150, moto: 75 },
    exceptions: "Αφαίρεση πινακίδων 70 ημέρες",
    keywords: ["στάθμευση", "αμεα", "ράμπα", "αναπηρία"]
  },
  {
    article: "Άρθρο 16 παρ.6 | Μη χρήση κράνους",
    desc: "Οδήγηση μοτοποδηλάτου/μοτοσικλέτας χωρίς προστατευτικό κράνος",
    category: "Ε3-Β",
    seso_points: 5,
    license_removal: 30,
    plates_removal: 0,
    payment_deadline_days: 60,
    payment_authority: "DOU",
    payment_required_for_return: true,
    fines: { car: 0, truck_low: 0, truck_high: 0, bus: 0, moto: 350 },
    exceptions: "Μη χρήση από συνεπιβάτη: Ε3-Α, πρόστιμο 350€, χωρίς αφαίρεση άδειας",
    keywords: ["κράνος", "μηχανή", "μοτοποδήλατο"]
  },
  {
    article: "Άρθρο 90 παρ.3 | Έλλειψη δελτίου τεχνικού ελέγχου (ΚΤΕΟ)",
    desc: "Κυκλοφορία χωρίς ισχύον Δελτίο Τεχνικού Ελέγχου (ΚΤΕΟ)",
    category: "Ε3-Β",
    seso_points: 0,
    license_removal: 0,
    plates_removal: 30,
    payment_deadline_days: 10,
    payment_authority: "DOU",
    payment_required_for_return: true,
    fines: { car: 350, truck_low: 350, truck_high: 700, bus: 700, moto: 175 },
    exceptions: "Επιστροφή στοιχείων μόνο με προσκόμιση ΔΤΕ. Για φορτηγά άνω 3,5τ: 700€",
    keywords: ["κτεο", "τεχνικός", "έλεγχος", "δελτίο"]
  },
  {
    article: "Άρθρο 17 παρ.2 | Χρήση κινητού τηλεφώνου",
    desc: "Χρήση κινητού τηλεφώνου κατά την οδήγηση χωρίς ανοικτή ακρόαση",
    category: "Ε3-Β",
    seso_points: 4,
    license_removal: 30,
    plates_removal: 0,
    payment_deadline_days: 60,
    payment_authority: "DOU",
    payment_required_for_return: true,
    fines: { car: 350, truck_low: 350, truck_high: 350, bus: 350, moto: 175 },
    exceptions: "",
    keywords: ["κινητό", "τηλέφωνο", "οδήγηση"]
  },
  {
    article: "Άρθρο 16 παρ.5 | Μη χρήση ζώνης ασφαλείας",
    desc: "Οδήγηση ή μεταφορά επιβατών χωρίς ζώνη ασφαλείας",
    category: "Ε3-Β",
    seso_points: 5,
    license_removal: 30,
    plates_removal: 0,
    payment_deadline_days: 60,
    payment_authority: "DOU",
    payment_required_for_return: true,
    fines: { car: 350, truck_low: 350, truck_high: 350, bus: 350, moto: 0 },
    exceptions: "",
    keywords: ["ζώνη", "ασφαλείας"]
  }
];